---
openapi: 3.0.0
info:
  title: ISIS
  description: ISIS Cloud Processing
  contact:
    name: Astrogeology Discussion Board
    url: https://astrodiscuss.usgs.gov
  license:
    name: The Unlicence
    url: https://unlicense.org
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /isis:
    post:
      operationId: isis_cloud.server.routes.isis.run_isis
      tags:
        - ISIS Commands
      summary: Run an ISIS command on the server
      requestBody:
        description: The ISIS command to run
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ISISCommand'
      responses:
        "200":
          description: The command executed successfully
        "500":
          description: The command threw an error
  /files:
    post:
      operationId: isis_cloud.server.routes.files.upload_file
      tags:
        - File Management
      summary: Send an ISIS input file to the server
      requestBody:
        description: The one or more files as a binary strings
        content:
          multipart/form-data:
            schema:
              type: object
              additionalProperties: true
              example: '{"J03_045994_1986_XN_18N282W.IMG": "<binary image data>"}'
      responses:
        "201":
          description: The files were copied to the server successfully
        "500":
          description: An error occurred during the file upload
  /files/{file_name}:
    get:
      operationId: isis_cloud.server.routes.files.retrieve_file
      tags:
        - File Management
      summary: Retrieve an output file generated by an ISIS command
      parameters:
        - name: file_name
          in: path
          description: The file to retrieve from the server
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: The file contents
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          description: The specified file does not exist
components:
  schemas:
    ISISCommand:
      required:
        - args
        - command
      type: object
      properties:
        command:
          type: string
          description: The ISIS command line program name
          example: mroctx2isis
        args:
          type: object
          additionalProperties: true
          example: '{"from": "my-mro.img", "to": "my-mro.cub"}'
