---
openapi: 3.0.0
info:
  title: ISIS
  description: ISIS Cloud Processing
  contact:
    name: Astrogeology Discussion Board
    url: https://astrodiscuss.usgs.gov
  license:
    name: The Unlicence
    url: https://unlicense.org
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /isis:
    post:
      operationId: isis_cloud.server.routes.isis.run_isis
      tags:
        - ISIS Programs
      summary: Run an ISIS program on the server
      requestBody:
        description: The ISIS program to run
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ISISProgram'
      responses:
        "200":
          description: The command executed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        "500":
          description: The command threw an error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
  /files:
    post:
      operationId: isis_cloud.server.routes.files.upload_file
      tags:
        - File Management
      summary: Send an ISIS input file to the server
      requestBody:
        description: The one or more files as a binary strings
        content:
          multipart/form-data:
            schema:
              type: object
              additionalProperties: true
              example: '{"J03_045994_1986_XN_18N282W.IMG": "<binary image data>"}'
      responses:
        "201":
          description: The files were copied to the server successfully
        "500":
          description: An error occurred during the file upload
  /files/{file_name}:
    get:
      operationId: isis_cloud.server.routes.files.retrieve_file
      tags:
        - File Management
      summary: Retrieve an output file generated by an ISIS command
      parameters:
        - name: file_name
          in: path
          description: The file to retrieve from the server
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: The file contents
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          description: The specified file does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
    delete:
      operationId: isis_cloud.server.routes.files.delete_file
      tags:
        - File Management
      summary: Delete a file on the ISIS server
      parameters:
        - name: file_name
          in: path
          description: The file to delete
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: The file was deleted successfully
        "404":
          description: The specified file does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
  /files/{file_name}/label:
    get:
      operationId: isis_cloud.server.routes.files.retrieve_file_label
      tags:
        - File Management
      summary: Retrieve the label of an ISIS cube as JSON
      description: See https://isis.astrogeology.usgs.gov/documents/LabelDictionary/LabelDictionary.html
      parameters:
        - name: file_name
          in: path
          description: The file
          required: true
          style: simple
          explode: false
          schema:
            type: string
            pattern: "^[^$]+\\.cub$"
      responses:
        "200":
          description: The label for the given cube
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ISISCubeLabel'
        "404":
          description: The specified file does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        "500":
          description: The specified file does not have a properly-formatted cube label
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
components:
  schemas:
    ISISProgram:
      type: object
      required:
        - args
        - program
      properties:
        program:
          type: string
          description: The ISIS command line program name
          example: mroctx2isis
        args:
          type: object
          additionalProperties: true
          example: '{"from": "my-mro.img", "to": "my-mro.cub"}'

    ISISCubeLabel:
      type: object
      required: [Core]
      additionalProperties: true
      properties:
        Core:
          type: object
          required:
            - StartByte
            - Format
            - Dimensions
            - Pixel
          properties:
            Core:
              type: string
            StartByte:
              type: integer
            Format:
              type: string
            TileSamples:
              type: integer
            TileLines:
              type: integer
            Dimensions:
              type: object
              required:
                - Samples
                - Lines
                - Bands
              properties:
                Samples:
                  type: integer
                Lines:
                  type: integer
                Bands:
                  type: integer
            Pixels:
              type: object
              required:
                - Type
                - ByteOrder
                - Base
                - Multiplier
              properties:
                Type:
                  type: string
                ByteOrder:
                  type: string
                Base:
                  type: number
                  format: float
                Multiplier:
                  type: number
                  format: float

    ResponseMessage:
      type: object
      required: [message]
      properties:
        message:
          type: string
          description: A message returned by the resource
          example: Command completed successfully
